In [1]:
from sklearn.linear_model import RidgeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [2]:
import pandas as pd

dataset = pd.read_csv('pipe2.csv')
dataset.head()

material    tomr  cf  c_wave_no  cd_radial  cw_circumferencial  crack
0         3  0.4217   2          1     0.6131              0.9991      1
1         6  0.7629   4         -2     0.3846              0.9982      1
2         5  0.1898   1         -7     0.6917              0.9982      1
3         2  0.4062   2         -2     0.5927              0.9980      1
4         6  0.8078   4        -10     0.9345              0.9980      1

In [3]:
Y = dataset.crack.to_numpy()
Y

array([1, 1, 1, ..., 0, 1, 1])

In [4]:
X = dataset.drop(['crack'] , axis=1).to_numpy()
X

array([[ 3.    ,  0.4217,  2.    ,  1.    ,  0.6131,  0.9991],
       [ 6.    ,  0.7629,  4.    , -2.    ,  0.3846,  0.9982],
       [ 5.    ,  0.1898,  1.    , -7.    ,  0.6917,  0.9982],
       ...,
       [ 3.    ,  0.0448,  1.    , -2.    ,  0.5649,  0.0254],
       [ 1.    ,  0.7149,  3.    ,  9.    ,  0.2688,  0.0253],
       [ 4.    ,  0.7759,  4.    ,  7.    ,  0.9258,  0.0252]])

In [5]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.15)

rc = RidgeClassifier()
print(rc)

alpha = 

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, random_state=None, solver='auto',
                tol=0.001)


rc.fit(xtrain, ytrain)
score = rc.score(xtrain, ytrain)
print("Score: ", score)

RidgeClassifier()
Score:  0.7289266221952698


In [6]:
cv_scores = cross_val_score(rc, xtrain, ytrain, cv=10)
print("CV average score: %.2f" % cv_scores.mean())

CV average score: 0.73


In [7]:
ypred = rc.predict(xtest)

cm = confusion_matrix(ytest, ypred)
print(cm)

[[ 37  54]
 [ 35 166]]


In [8]:
cr = classification_report(ytest, ypred)
print(cr)

              precision    recall  f1-score   support

           0       0.51      0.41      0.45        91
           1       0.75      0.83      0.79       201

    accuracy                           0.70       292
   macro avg       0.63      0.62      0.62       292
weighted avg       0.68      0.70      0.68       292

